# let's see if comments work

language: ruby
rvm:
  - 1.9.3
bundler_args: "--without development"
before_install:
  - gem install bundler --pre
before_script:
  - "cp config/database.example.yml config/database.yml"
  - RAILS_ENV=test rake bundle exec rake db:migrate
script: true
notifications:
  irc: "irc.freenode.org#travis"
  campfire:
    secure: "JJezWGD9KJY/LC2aznI3Zyohy31VTIhcTKX7RWR4C/C8YKbW9kZv3xV6Vn11\nSHxJTeZo6st2Bpv6tjlWZ+HCR09kyCNavIChedla3+oHOiuL0D4gSo+gkTNW\nUKYZz9mcQUd9RoQpTeyxvdvX+l7z62/7JwFA7txHOqxbTS8jrjc="
