development:
  adapter: postgresql
  encoding: unicode
  database: travis_development
  pool: 5

test: &test
  adapter: postgresql
  encoding: unicode
  database: travis_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: travis_production
  pool: 5

jasmine:
  <<: *test

cucumber:
  <<: *test
