:port: 8080
:debug: false

# :subscribe_url: http://localhost:3000/socky/subscribe
# :unsubscribe_url: http://localhost:3000/socky/unsubscribe

:secret: my_secret_key

:secure: false

# :timeout: 3

:log_path: log/socky.log
# :pid_path: /var/run/socky.pid

# :tls_options:
#   :private_key_file: /private/key
#   :cert_chain_file: /ssl/certificate

