oauth2: &oauth2
  authorization_server: https://github.com
  requested_scope: user
  authorize_path: login/oauth/authorize
  access_token_path: login/oauth/access_token
  user_attributes_path: api/v2/json/user/show
  user_attribute_uid_key: user/login

production:
  queues:
    - slug: rails/rails
      queue: rails
    - target: erlang
      queue: erlang
  notifications:
    - pusher
    - worker
    - email
    - irc
    - webhook
  redis:
    url: redis://YOUR_REDIS_URL
  pusher:
    app_id: YOUR_PUSHER_APP_ID
    key:    YOUR_PUSHER_KEY
    secret: YOUR_PUSHER_SECRET
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET
    <<: *oauth2
  hoptoad:
    key: YOUR_HOPTOAD_KEY
  rails:
    # You get a Travis token on your application's profile page by signing in to your application via Github OAuth2.
    url: "YOUR_GITHUB_USERNAME:YOUR_TRAVIS_TOKEN@YOUR_APP.heroku.com"

development:
  notifications:
    - pusher
    - worker
  redis:
    url: redis://localhost:6379
  amqp:
    vhost: travisci.development
    username: travisci_server
    password: travisci_server_password
  pusher:
    app_id: YOUR_PUSHER_APP_ID
    key:    YOUR_PUSHER_KEY
    secret: YOUR_PUSHER_SECRET
  rails:
    host: localhost:3000
  oauth2:
    client_id: YOUR_GITHUB_CLIENT_ID
    client_secret: YOUR_GITHUB_CLIENT_SECRET

test:
  redis:
    url: redis://localhost:6379
